// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcFQKKEKA-kfLRh6eA2SWhcAT0jSais0',
    appId: '1:40314714081:web:54c663e7d35d12357184a0',
    messagingSenderId: '40314714081',
    projectId: 'mapclassexample-34c61',
    authDomain: 'mapclassexample-34c61.firebaseapp.com',
    databaseURL: 'https://mapclassexample-34c61-default-rtdb.firebaseio.com',
    storageBucket: 'mapclassexample-34c61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx09O8jswWLqY7F1aFpDKfuTrox-kqADQ',
    appId: '1:40314714081:android:4967fd581481ded77184a0',
    messagingSenderId: '40314714081',
    projectId: 'mapclassexample-34c61',
    databaseURL: 'https://mapclassexample-34c61-default-rtdb.firebaseio.com',
    storageBucket: 'mapclassexample-34c61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFthXQTyB2AjzhbSh1LEhcRkRiBke_t8',
    appId: '1:40314714081:ios:dac96d7171c9c12d7184a0',
    messagingSenderId: '40314714081',
    projectId: 'mapclassexample-34c61',
    databaseURL: 'https://mapclassexample-34c61-default-rtdb.firebaseio.com',
    storageBucket: 'mapclassexample-34c61.appspot.com',
    iosClientId: '40314714081-oe44s9mdjso440g8jmreunpaju1noijh.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachingExampleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFthXQTyB2AjzhbSh1LEhcRkRiBke_t8',
    appId: '1:40314714081:ios:8d403617c570a65e7184a0',
    messagingSenderId: '40314714081',
    projectId: 'mapclassexample-34c61',
    databaseURL: 'https://mapclassexample-34c61-default-rtdb.firebaseio.com',
    storageBucket: 'mapclassexample-34c61.appspot.com',
    iosClientId: '40314714081-s4nkdrmkd1rmmol40ndi76rcvggnijha.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachingExampleFlutter.RunnerTests',
  );
}
